apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservas-deployment
spec:
    replicas: 1
    selector:
      matchLabels:
        app: reservas
    template:
        metadata:
          labels:
            app: reservas
        spec:
          containers:
            - name: reservas-api
              image: reservas-api:local
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reservas-service
spec:
    type: NodePort
    selector:
      app: reservas
    ports:
      - port: 80
        targetPort: 80
        nodePort: 30080
